# must be absolute path
cfg_directory: "{{ playbook_dir }}/cfg"
pki_directory: "{{ playbook_dir }}/pki"

# enable firewall
# - the feature is experimental
# - not fully implemented
# - works currently only on centos
firewall_enabled: false

# password for keepalived authentication
keepalived_password: secret42

# virtual IP managed by keepalived
kube_apiserver_public_ip: 192.168.100.50
# Used for internal cluster conf (flannel)
iface_regex: 192\.168\.100\.

kubernetes_version: 1.11.3
etcd_version: 3.3.9
runc_version: 1.0.0-rc5
critools_version: 1.11.1
cniplugins_version: 0.7.1
containerd_version: 1.1.4
