- name: capture config file stats
  stat:
    path: "{{ cfg_directory }}/kube-scheduler.kubeconfig"
  register: cfg

- name: set cluster
  shell: >
    kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority="{{ pki_directory }}/ca.pem" \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ cfg_directory }}"
  when: cfg.stat.exists == False

- name: set credentials
  shell: >
    kubectl config set-credentials system:kube-scheduler \
    --client-certificate="{{ pki_directory }}/kube-scheduler.pem" \
    --client-key="{{ pki_directory }}/kube-scheduler-key.pem" \
    --embed-certs=true \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ cfg_directory }}"
  when: cfg.stat.exists == False

- name: set context
  shell: >
    kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:kube-scheduler \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ cfg_directory }}"
  when: cfg.stat.exists == False

- name: use default context
  shell: >
    kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ cfg_directory }}"
  when: cfg.stat.exists == False