- name: install kubectl (MacOSX)
  homebrew:
    name: kubectl
  when: ansible_distribution == "MacOSX"

- name: install kubectl (Linux)
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{kubernetes_version}}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
  when: ansible_system == "Linux"

- name: create configuration directory
  file:
    path: "{{ cfg_directory }}"
    state: directory

- name: generate kubelet configuration
  include: kubelet.yml
  with_items: "{{ groups['workers'] }}"

- name: generate kube-proxy configuration
  include: kube-proxy.yml

- name: generate kube-controller-manager configuration
  include: kube-controller-manager.yml

- name: generate kube-scheduler configuration
  include: kube-scheduler.yml

- name: generate admin configuration
  include: admin.yml