- name: install required packages (Ubuntu)
  apt:
    name:
      - socat
      - conntrack
      - ipset
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install required packages (CentOS)
  yum:
    name:
      - socat
      - conntrack
      - ipset
    state: present
  when: ansible_distribution == "CentOS"

- name: download kubernetes worker components
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{kubernetes_version}}/bin/linux/amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: kubernetes
    group: kubernetes
    mode: 0750
  with_items:
    - kubelet
    - kube-proxy
    - kubectl

- name: download runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{runc_version}}/runc.amd64
    dest: /usr/local/bin/runc
    owner: kubernetes
    group: kubernetes
    mode: 0750

- name: download crictl
  unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{critools_version}}/crictl-v{{critools_version}}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/crictl
    owner: root
    group: root
    mode: 0750

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/cni
    - /opt/cni/bin
    - /opt/cni/net.d
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes
    - /etc/containerd

- name: download cni-plugins
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{cniplugins_version}}/cni-plugins-amd64-v{{cniplugins_version}}.tgz
    dest: /opt/cni/bin/
    remote_src: yes
    creates: /opt/cni/bin/flannel

- name: download containerd
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v{{containerd_version}}/containerd-{{containerd_version}}.linux-amd64.tar.gz
    dest: /root
    remote_src: yes
    creates: /root/bin/containerd

- name: copy containerd binaries
  copy:
    src: /root/bin/{{item}}
    dest: /bin/{{item}}
    mode: 0750
    owner: root
    group: root
    remote_src: yes
  with_items:
   - containerd
   - containerd-release
   - containerd-shim
   - containerd-stress
   - ctr

- name: copy containerd configuration
  copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
  notify:
    - restart containerd service

- name: create containerd service
  copy:
    src: files/containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: 0644
  notify:
    - reload systemd configs
    - restart containerd service

- name: copy kubelet certificates
  copy:
    src: "{{pki_directory}}/{{ inventory_hostname }}{{item}}"
    dest: "/var/lib/kubelet/{{ inventory_hostname }}{{item}}"
    owner: kubernetes
    group: kubernetes
    mode: 0640
  with_items:
    - "-key.pem"
    - ".pem"

- name: copy kubelet configuration
  copy:
    src: "{{cfg_directory}}/{{ inventory_hostname }}.kubeconfig"
    dest: "/var/lib/kubelet/kubeconfig"
    owner: kubernetes
    group: kubernetes
    mode: 0640

- name: copy ca
  copy:
    src: "{{pki_directory}}/ca.pem"
    dest: "/var/lib/kubernetes/ca.pem"
    owner: kubernetes
    group: kubernetes
    mode: 0640

- name: set kubelet resolv.conf to /etc/resolv.conf
  set_fact:
    resolvConf: /etc/resolv.conf

- name: set kubelet resolv.conf to /etc/resolv.conf (Ubuntu 18.04)
  set_fact:
    resolvConf: /run/systemd/resolve/resolv.conf
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

- name: create kubelet configuration
  template:
    src: templates/kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml
    owner: kubernetes
    group: kubernetes
    mode: 0640
  notify: restart kubelet service

- name: create kubelet service
  template:
    src: templates/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    mode: 0644
  notify:
    - reload systemd configs
    - restart kubelet service

- name: copy kube-proxy kubeconfig
  copy:
    src: "{{cfg_directory}}/kube-proxy.kubeconfig"
    dest: "/var/lib/kube-proxy/kubeconfig"
    owner: kubernetes
    group: kubernetes
    mode: 0640

- name: copy kube-proxy configuration
  copy:
    src: files/kube-proxy-config.yaml
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml
    owner: kubernetes
    group: kubernetes
    mode: 0640

- name: create kube-proxy service
  template:
    src: templates/kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
    mode: 0644
  notify:
    - reload systemd configs
    - restart kube-proxy service

- name: disable swap
  include: swap.yml

- name: enable kubernetes worker services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    daemon_reload: yes
  with_items:
    - containerd
    - kubelet
    - kube-proxy
