- name: create kubernetes group
  group:
    name: kubernetes

- name: create user for kubernetes service
  user:
    name: kubernetes
    group: kubernetes
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
