- name: find target interface for keepalived
  set_fact:
    keepalived_interface: "{{ item }}"
  when: hostvars[inventory_hostname]['ansible_%s' % item].ipv4.address == hostvars[inventory_hostname].ansible_host
  with_items:
    - "{{ ansible_interfaces }}"

- name: create keepalived scripts
  group:
    name: keepalived_script

- name: create user for keepalived scripts
  user:
    name: keepalived_script
    group: keepalived_script
    create_home: no
    shell: /bin/bash
    system: yes

- name: install keepalived package (Ubuntu)
  apt:
    name: keepalived
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install keepalived package (CentOS)
  yum:
    name: keepalived
    state: present
  when: ansible_distribution == "CentOS"

- name: create keepalived configuration
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived service

- name: ensure keepalived service is running and enabled
  systemd:
    name: keepalived
    state: started
    enabled: yes