- name: reload systemd configs
  systemd:
    daemon_reload: yes

- name: restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: restart kubelet service
  systemd:
    name: kubelet
    state: restarted

- name: restart kube-proxy service
  systemd:
    name: kube-proxy
    state: restarted